<a href="https://colab.research.google.com/github/mim-1999/ames-housing-regression/blob/main/Ames_Housing_EDA_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Load dataset and understand it

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Ames_Housing_Project/train.csv')
print(df.head().to_string())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition  SalePrice
0   1          60       RL         65.0     8450   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     2Story            7            5       2003          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace       196.0        Gd        TA      PConc       Gd       TA           No          GLQ         706          Unf           0        150          856    GasA        Ex          Y      SBrkr       856       854             0       1710             1             0         2         1             3             1          Gd             8        Typ           0         NaN     Attchd       2003.0          RFn           2         548         TA         TA          Y           0           61              0          0            0         0    NaN   NaN         NaN        0       2    2008       WD        Normal     208500
1   2          20       RL         80.0     9600   Pave   NaN      Reg         Lvl    AllPub       FR2       Gtl      Veenker      Feedr       Norm     1Fam     1Story            6            8       1976          1976     Gable  CompShg     MetalSd     MetalSd        NaN         0.0        TA        TA     CBlock       Gd       TA           Gd          ALQ         978          Unf           0        284         1262    GasA        Ex          Y      SBrkr      1262         0             0       1262             0             1         2         0             3             1          TA             6        Typ           1          TA     Attchd       1976.0          RFn           2         460         TA         TA          Y         298            0              0          0            0         0    NaN   NaN         NaN        0       5    2007       WD        Normal     181500
2   3          60       RL         68.0    11250   Pave   NaN      IR1         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     2Story            7            5       2001          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace       162.0        Gd        TA      PConc       Gd       TA           Mn          GLQ         486          Unf           0        434          920    GasA        Ex          Y      SBrkr       920       866             0       1786             1             0         2         1             3             1          Gd             6        Typ           1          TA     Attchd       2001.0          RFn           2         608         TA         TA          Y           0           42              0          0            0         0    NaN   NaN         NaN        0       9    2008       WD        Normal     223500
3   4          70       RL         60.0     9550   Pave   NaN      IR1         Lvl    AllPub    Corner       Gtl      Crawfor       Norm       Norm     1Fam     2Story            7            5       1915          1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN         0.0        TA        TA     BrkTil       TA       Gd           No          ALQ         216          Unf           0        540          756    GasA        Gd          Y      SBrkr       961       756             0       1717             1             0         1         0             3             1          Gd             7        Typ           1          Gd     Detchd       1998.0          Unf           3         642         TA         TA          Y           0           35            272          0            0         0    NaN   NaN         NaN        0       2    2006       WD       Abnorml     140000
4   5          60       RL         84.0    14260   Pave   NaN      IR1         Lvl    AllPub       FR2       Gtl      NoRidge       Norm       Norm     1Fam     2Story            8            5       2000          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace       350.0        Gd        TA      PConc       Gd       TA           Av          GLQ         655          Unf           0        490         1145    GasA        Ex          Y      SBrkr      1145      1053             0       2198             1             0         2         1             4             1          Gd             9        Typ           1          TA     Attchd       2000.0          RFn           3         836         TA         TA          Y         192           84              0          0            0         0    NaN   NaN         NaN        0      12    2008       WD        Normal     250000

In [5]:
df.shape

(1460, 81)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

## check missing values

In [7]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [18]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print(missing)

LotFrontage    259
GarageYrBlt     81
MasVnrArea       8
Electrical       1
dtype: int64

In [19]:
cols_with_missing = missing.index.tolist()
print(df.loc[df[cols_with_missing].isnull().any(axis=1), cols_with_missing].to_string())

      LotFrontage  GarageYrBlt  MasVnrArea Electrical
7             NaN       1973.0       240.0      SBrkr
12            NaN       1962.0         0.0      SBrkr
14            NaN       1960.0       212.0      SBrkr
16            NaN       1970.0       180.0      SBrkr
24            NaN       1968.0         0.0      SBrkr
31            NaN       1966.0         0.0      SBrkr
39           65.0          NaN         0.0      FuseP
42            NaN       1983.0         0.0      SBrkr
43            NaN       1977.0         0.0      SBrkr
48           33.0          NaN         0.0      SBrkr
50            NaN       1997.0         0.0      SBrkr
64            NaN       1998.0       573.0      SBrkr
66            NaN       1970.0       287.0      SBrkr
76            NaN       1956.0         0.0      FuseA
78           72.0          NaN         0.0      SBrkr
84            NaN       1995.0        22.0      SBrkr
88          105.0          NaN         0.0      SBrkr
89           60.0          NaN         0.0      SBrkr
95            NaN       1993.0        68.0      SBrkr
99           77.0          NaN         0.0      SBrkr
100           NaN       1977.0        28.0      SBrkr
104           NaN       1951.0       600.0      FuseF
108          85.0          NaN         0.0      FuseF
111           NaN       2000.0         0.0      SBrkr
113           NaN       1953.0       184.0      SBrkr
116           NaN       1962.0       116.0      SBrkr
120           NaN       1969.0         0.0      SBrkr
125          60.0          NaN         0.0      SBrkr
126           NaN       1977.0         0.0      SBrkr
127          55.0          NaN         0.0      SBrkr
131           NaN       2000.0        40.0      SBrkr
133           NaN       2001.0       136.0      SBrkr
136           NaN       1967.0       196.0      SBrkr
140          70.0          NaN         0.0      SBrkr
147           NaN       2001.0       180.0      SBrkr
148          63.0          NaN       120.0      SBrkr
149           NaN       1936.0         0.0      FuseA
152           NaN       1971.0       252.0      SBrkr
153           NaN       1960.0         0.0      SBrkr
155          60.0          NaN         0.0      FuseF
160           NaN       1984.0         0.0      SBrkr
163          55.0          NaN         0.0      SBrkr
165          62.0          NaN         0.0      SBrkr
166           NaN       1955.0         0.0      FuseA
169           NaN       1981.0       653.0      SBrkr
170           NaN       1991.0         0.0      SBrkr
177           NaN       1958.0         0.0      SBrkr
180           NaN       2000.0       456.0      SBrkr
186           NaN       1990.0         0.0      SBrkr
191           NaN       1972.0       138.0      SBrkr
198          92.0          NaN         0.0      SBrkr
203           NaN       2004.0       205.0      SBrkr
207           NaN       1960.0         0.0      SBrkr
208           NaN       1988.0       128.0      SBrkr
210          67.0          NaN         0.0      FuseA
214           NaN       1977.0       153.0      SBrkr
218           NaN       1939.0       312.0      SBrkr
221           NaN       2002.0         0.0      SBrkr
234           NaN       2002.0         NaN      SBrkr
237           NaN       1993.0         0.0      SBrkr
241          40.0          NaN         0.0      SBrkr
244           NaN       1994.0         0.0      SBrkr
249           NaN       1958.0       472.0      SBrkr
250          55.0          NaN         0.0      SBrkr
269           NaN       1987.0       174.0      SBrkr
287           NaN          NaN         0.0      SBrkr
288           NaN       1970.0        31.0      SBrkr
291          55.0          NaN         0.0      SBrkr
293           NaN       1977.0        34.0      SBrkr
307           NaN          NaN         0.0      FuseA
308           NaN       1961.0         0.0      SBrkr
310           NaN       1993.0       112.0      SBrkr
319           NaN       1980.0       225.0      SBrkr
328           NaN       1930.0         0.0      FuseA
330           NaN       2002.0        84.0      SBrkr
335           NaN       1965.0         0.0      SBrkr
342           NaN       1949.0       340.0      FuseA
346           NaN       1960.0         0.0      SBrkr
347           NaN       1960.0        30.0      FuseA
351           NaN       1986.0         0.0      SBrkr
356           NaN       1992.0       106.0      SBrkr
360           NaN       1978.0         0.0      SBrkr
361           NaN       1940.0         0.0      SBrkr
364           NaN       1976.0       120.0      SBrkr
366           NaN       1963.0       247.0      SBrkr
369           NaN       1997.0         0.0      SBrkr
370           NaN       2000.0         0.0      SBrkr
375           NaN          NaN         0.0      FuseA
384           NaN       1992.0         0.0      SBrkr
386          58.0          NaN         0.0      SBrkr
392           NaN       1959.0         0.0      SBrkr
393           NaN          NaN         0.0      FuseA
404           NaN       1995.0         0.0      SBrkr
405           NaN       1993.0         0.0      SBrkr
412           NaN       2009.0       432.0      SBrkr
421           NaN       1977.0       126.0      SBrkr
426           NaN       1989.0       145.0      SBrkr
431          60.0          NaN         0.0      SBrkr
434          21.0          NaN         0.0      SBrkr
441          92.0          NaN       270.0      FuseF
447           NaN       1998.0         0.0      SBrkr
452           NaN       1996.0        42.0      SBrkr
457           NaN       1954.0         0.0      SBrkr
458           NaN       1925.0         0.0      SBrkr
459           NaN       1950.0       161.0      SBrkr
464          60.0          NaN       136.0      SBrkr
465           NaN       2004.0        18.0      SBrkr
470           NaN       1985.0         0.0      SBrkr
484           NaN       1963.0         0.0      SBrkr
490           NaN       1976.0         0.0      SBrkr
495          60.0          NaN         0.0      FuseA
496           NaN       1992.0         0.0      SBrkr
516           NaN       1972.0       333.0      SBrkr
518           NaN       1998.0         0.0      SBrkr
520          60.0          NaN         0.0      FuseA
528          58.0          NaN         0.0      SBrkr
529           NaN       1975.0         NaN      SBrkr
533          50.0          NaN         0.0      FuseF
535          70.0          NaN         0.0      SBrkr
537           NaN       1980.0         0.0      SBrkr
538           NaN       1968.0       188.0      SBrkr
539           NaN       2001.0       479.0      SBrkr
541           NaN       2000.0        72.0      SBrkr
545           NaN       1988.0       178.0      SBrkr
559           NaN       2003.0        18.0      SBrkr
560           NaN       1957.0       180.0      SBrkr
562          63.0          NaN         0.0      SBrkr
564           NaN       1992.0         0.0      SBrkr
569           NaN       1979.0         0.0      SBrkr
580           NaN       1960.0        85.0      SBrkr
582          81.0          NaN       104.0      SBrkr
593           NaN       2003.0       170.0      SBrkr
610           NaN       2000.0       204.0      SBrkr
611           NaN       1978.0       233.0      SBrkr
612           NaN       2001.0       108.0      SBrkr
613          70.0          NaN         0.0      SBrkr
614          21.0          NaN         0.0      SBrkr
616           NaN       2002.0         0.0      SBrkr
620          45.0          NaN         0.0      FuseF
623           NaN       2000.0       513.0      SBrkr
626           NaN       1960.0         0.0      SBrkr
635          60.0          NaN         0.0      FuseA
636          51.0          NaN         0.0      FuseA
638          67.0          NaN         0.0      FuseA
641           NaN       2001.0         0.0      SBrkr
645           NaN       1979.0         0.0      SBrkr
649          21.0          NaN         0.0      SBrkr
650          65.0       2007.0         NaN      SBrkr
660           NaN       1976.0       233.0      SBrkr
666           NaN       1965.0       113.0      SBrkr
668           NaN       1999.0         0.0      SBrkr
672           NaN       1977.0         0.0      SBrkr
679           NaN       1963.0        57.0      SBrkr
682           NaN       1996.0         0.0      SBrkr
685           NaN       1984.0         0.0      SBrkr
687           NaN       2004.0         0.0      SBrkr
690           NaN       2004.0       147.0      SBrkr
705          70.0          NaN         0.0      SBrkr
706           NaN       1971.0       351.0      SBrkr
709           NaN       1966.0        41.0      SBrkr
710          56.0          NaN         0.0      SBrkr
714           NaN       1976.0       289.0      SBrkr
720           NaN       1985.0         0.0      SBrkr
721           NaN       2004.0       169.0      SBrkr
726           NaN       1988.0       260.0      SBrkr
734           NaN       1968.0         0.0      SBrkr
738          60.0          NaN         0.0      SBrkr
745           NaN       1994.0       289.0      SBrkr
746           NaN       2000.0         0.0      SBrkr
750          55.0          NaN         0.0      SBrkr
751           NaN       2003.0         0.0      SBrkr
757           NaN       1978.0       328.0      SBrkr
770           NaN       1983.0         0.0      SBrkr
783           NaN       1978.0       104.0      SBrkr
784          35.0          NaN         0.0      SBrkr
785           NaN       1967.0         0.0      SBrkr
789           NaN       1966.0       157.0      SBrkr
791           NaN       1976.0         0.0      SBrkr
794           NaN       1994.0         0.0      SBrkr
811           NaN       2004.0       169.0      SBrkr
816           NaN       1954.0         0.0      SBrkr
817           NaN       2002.0       148.0      SBrkr
822           NaN       2003.0         0.0      SBrkr
826          50.0          NaN         0.0      SBrkr
828           NaN       1967.0         0.0      SBrkr
840           NaN       1934.0         0.0      SBrkr
843          80.0          NaN         0.0      SBrkr
845           NaN       1975.0         0.0      SBrkr
851           NaN       2003.0        40.0      SBrkr
853           NaN       1964.0       115.0      SBrkr
855           NaN       1962.0         0.0      SBrkr
856           NaN       1981.0         0.0      SBrkr
859           NaN       1968.0       220.0      SBrkr
865           NaN       1973.0        76.0      SBrkr
868           NaN       1979.0         0.0      SBrkr
879           NaN       1978.0        90.0      SBrkr
882           NaN       1993.0         0.0      SBrkr
893           NaN       1954.0         0.0      SBrkr
900           NaN       1979.0         0.0      SBrkr
904           NaN       1967.0        75.0      SBrkr
908           NaN       1983.0         0.0      SBrkr
911           NaN       1978.0         0.0      SBrkr
917           NaN       1956.0         0.0      FuseA
921          67.0          NaN         0.0      SBrkr
925           NaN       1977.0         0.0      SBrkr
927           NaN       1968.0       342.0      SBrkr
928           NaN       2001.0         0.0      SBrkr
929           NaN       1997.0       285.0      SBrkr
936          67.0       2003.0         NaN      SBrkr
939           NaN       1940.0         0.0      SBrkr
941           NaN       1999.0       298.0      SBrkr
942          42.0          NaN         0.0      SBrkr
944           NaN       1958.0       541.0      FuseA
953           NaN       1969.0       232.0      SBrkr
954          35.0          NaN       250.0      SBrkr
960          50.0          NaN         0.0      SBrkr
961           NaN       1977.0       424.0      SBrkr
967           NaN       1955.0       151.0      SBrkr
968          50.0          NaN         0.0      SBrkr
970          60.0          NaN         0.0      FuseA
973          95.0       2007.0         NaN      SBrkr
975           NaN       2000.0         0.0      SBrkr
976          51.0          NaN         0.0      FuseA
977          35.0       2007.0         NaN      SBrkr
980           NaN       1961.0       210.0      SBrkr
983           NaN       2002.0         0.0      SBrkr
988           NaN       1976.0       298.0      SBrkr
996           NaN       1961.0         0.0      SBrkr
997           NaN       1970.0       571.0      SBrkr
1003          NaN       1976.0       164.0      SBrkr
1006          NaN       1970.0         0.0      SBrkr
1009         60.0          NaN         0.0      SBrkr
1011         75.0          NaN         0.0      SBrkr
1017          NaN       1984.0         0.0      SBrkr
1018          NaN       1991.0        76.0      SBrkr
1024          NaN       1976.0         0.0      SBrkr
1030          NaN          NaN         0.0      SBrkr
1032          NaN       1993.0         0.0      SBrkr
1033          NaN       2002.0       295.0      SBrkr
1035          NaN       1957.0         0.0      SBrkr
1037          NaN       2001.0       396.0      SBrkr
1038         21.0          NaN         0.0      SBrkr
1041          NaN       1966.0       252.0      SBrkr
1045          NaN       1955.0         0.0      FuseA
1057          NaN       1994.0         0.0      SBrkr
1059          NaN       1977.0       480.0      SBrkr
1064          NaN       1966.0       200.0      SBrkr
1077          NaN       1969.0         0.0      SBrkr
1084          NaN       1995.0         0.0      SBrkr
1086          NaN       1973.0         0.0      SBrkr
1096         60.0          NaN         0.0      SBrkr
1097          NaN       1987.0         0.0      SBrkr
1108          NaN       2000.0         0.0      SBrkr
1110          NaN       1995.0         0.0      SBrkr
1116          NaN       2002.0         0.0      SBrkr
1122          NaN       1956.0         0.0      FuseA
1123         50.0          NaN         0.0      SBrkr
1124          NaN       1992.0       170.0      SBrkr
1131         63.0          NaN         0.0      SBrkr
1137         54.0          NaN         0.0      SBrkr
1138          NaN       1977.0         0.0      SBrkr
1141          NaN       1976.0        44.0      SBrkr
1143          NaN          NaN         0.0      SBrkr
1146          NaN       1985.0        85.0      SBrkr
1148          NaN       1982.0         0.0      SBrkr
1153          NaN       2002.0         0.0      SBrkr
1154          NaN       1965.0       288.0      SBrkr
1161          NaN       1993.0        72.0      SBrkr
1164          NaN       1978.0         0.0      SBrkr
1173        138.0          NaN         0.0      SBrkr
1177          NaN       1926.0         0.0      SBrkr
1179         77.0          NaN         0.0      SBrkr
1180          NaN       1990.0         0.0      SBrkr
1190          NaN       1975.0       149.0      SBrkr
1193          NaN       1999.0       425.0      SBrkr
1206          NaN       1966.0         0.0      SBrkr
1213          NaN       1965.0         0.0      SBrkr
1218         52.0          NaN         0.0      SBrkr
1219         21.0          NaN       236.0      SBrkr
1230          NaN       1977.0         1.0      SBrkr
1233          NaN       1959.0       180.0      SBrkr
1234         55.0          NaN         0.0      FuseA
1243        107.0       2006.0         NaN      SBrkr
1244          NaN       1931.0         0.0      SBrkr
1247          NaN       1976.0       335.0      SBrkr
1251          NaN       2003.0       163.0      SBrkr
1253          NaN       1974.0         0.0      SBrkr
1257         56.0          NaN         0.0      SBrkr
1260          NaN       1999.0         0.0      SBrkr
1262          NaN       1957.0         0.0      FuseA
1268          NaN       1982.0       632.0      SBrkr
1270          NaN       1979.0         0.0      SBrkr
1271          NaN       1968.0         0.0      SBrkr
1272          NaN       1965.0       114.0      SBrkr
1276          NaN       1972.0         0.0      SBrkr
1277          NaN       1967.0       359.0      SBrkr
1278         75.0       2002.0         NaN      SBrkr
1283         94.0          NaN         0.0      SBrkr
1286          NaN       1963.0       451.0      SBrkr
1287          NaN       1964.0       621.0      SBrkr
1290          NaN       1964.0        86.0      SBrkr
1300          NaN       1999.0       344.0      SBrkr
1301          NaN       1942.0         0.0      SBrkr
1309          NaN       1991.0        88.0      SBrkr
1312          NaN       1990.0       336.0      SBrkr
1318          NaN       2001.0       178.0      SBrkr
1321          NaN       1955.0         0.0      SBrkr
1323         50.0          NaN         0.0      SBrkr
1325         40.0          NaN         0.0      SBrkr
1326         70.0          NaN         0.0      SBrkr
1337        153.0          NaN         0.0      FuseA
1342          NaN       2002.0       149.0      SBrkr
1346          NaN       1968.0         0.0      SBrkr
1348          NaN       1998.0         0.0      SBrkr
1349         50.0          NaN         0.0      SBrkr
1354          NaN       2000.0         0.0      SBrkr
1356          NaN       1966.0        65.0      SBrkr
1357          NaN       1971.0         0.0      SBrkr
1358          NaN       2000.0       216.0      SBrkr
1362          NaN       1920.0         0.0      SBrkr
1365          NaN       2000.0         0.0      SBrkr
1368          NaN       2003.0       170.0      SBrkr
1373          NaN       2001.0       705.0      SBrkr
1379         73.0       2007.0         0.0        NaN
1381          NaN       1970.0         0.0      SBrkr
1383          NaN       2007.0         0.0      SBrkr
1396          NaN       1966.0         0.0      SBrkr
1407          NaN          NaN         0.0      SBrkr
1417          NaN       1998.0       731.0      SBrkr
1419          NaN       1969.0       312.0      SBrkr
1423          NaN       1966.0         0.0      SBrkr
1424          NaN       1970.0         0.0      SBrkr
1429          NaN       1981.0       310.0      SBrkr
1431          NaN       1976.0         0.0      SBrkr
1441          NaN       2004.0       147.0      SBrkr
1443          NaN       1916.0         0.0      FuseF
1446          NaN       1962.0       189.0      SBrkr
1449         21.0          NaN         0.0      SBrkr
1450         60.0          NaN         0.0      SBrkr
1453         90.0          NaN         0.0      SBrkr

In [20]:
basement_cols = ['BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtCond', 'BsmtFinType1']
#df[df[basement_cols].isnull().any(axis=1)][basement_cols]
df.loc[df[basement_cols].isnull().any(axis=1),basement_cols]

Empty DataFrame
Columns: [BsmtExposure, BsmtFinType2, BsmtQual, BsmtCond, BsmtFinType1]
Index: []

## Handle missing values

In [13]:
basement_cols = ['BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtCond', 'BsmtFinType1']
for col in basement_cols:
    df[col] = df[col].fillna('None')

In [15]:
none_cols = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu',
             'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'MasVnrType']
for col in none_cols:
    df[col] = df[col].fillna('None')

In [21]:
df['GarageYrBlt'] = df['GarageYrBlt'].fillna(0)

In [22]:
df['LotFrontage'] = df['LotFrontage'].fillna(df['LotFrontage'].median())
df['MasVnrArea'] = df['MasVnrArea'].fillna(0)
df['Electrical'] = df['Electrical'].fillna(df['Electrical'].mode()[0])

In [25]:
df.isnull().sum().sum()

np.int64(0)