<a href="https://colab.research.google.com/github/mim-1999/ames-housing-regression/blob/main/Ames_Housing_EDA_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [22]:
# import libraries
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
# Create the 'images' directory if it doesn't exist
os.makedirs('images', exist_ok=True)

## Load dataset and understand it

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Ames_Housing_Project/train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df.shape

(1460, 81)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

## check missing values

In [6]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [7]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print(missing)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

In [8]:
cols_with_missing = missing.index.tolist()
print(df.loc[df[cols_with_missing].isnull().any(axis=1), cols_with_missing].to_string())

     PoolQC MiscFeature Alley  Fence MasVnrType FireplaceQu  LotFrontage GarageType  GarageYrBlt GarageFinish GarageQual GarageCond BsmtExposure BsmtFinType2 BsmtQual BsmtCond BsmtFinType1  MasVnrArea Electrical
0       NaN         NaN   NaN    NaN    BrkFace         NaN         65.0     Attchd       2003.0          RFn         TA         TA           No          Unf       Gd       TA          GLQ       196.0      SBrkr
1       NaN         NaN   NaN    NaN        NaN          TA         80.0     Attchd       1976.0          RFn         TA         TA           Gd          Unf       Gd       TA          ALQ         0.0      SBrkr
2       NaN         NaN   NaN    NaN    BrkFace          TA         68.0     Attchd       2001.0          RFn         TA         TA           Mn          Unf       Gd       TA          GLQ       162.0      SBrkr
3       NaN         NaN   NaN    NaN        NaN          Gd         60.0     Detchd       1998.0          Unf         TA         TA           No          Unf       TA       Gd          ALQ         0.0      SBrkr
4       NaN         NaN   NaN    NaN    BrkFace          TA         84.0     Attchd       2000.0          RFn         TA         TA           Av          Unf       Gd       TA          GLQ       350.0      SBrkr
5       NaN        Shed   NaN  MnPrv        NaN         NaN         85.0     Attchd       1993.0          Unf         TA         TA           No          Unf       Gd       TA          GLQ         0.0      SBrkr
6       NaN         NaN   NaN    NaN      Stone          Gd         75.0     Attchd       2004.0          RFn         TA         TA           Av          Unf       Ex       TA          GLQ       186.0      SBrkr
7       NaN        Shed   NaN    NaN      Stone          TA          NaN     Attchd       1973.0          RFn         TA         TA           Mn          BLQ       Gd       TA          ALQ       240.0      SBrkr
8       NaN         NaN   NaN    NaN        NaN          TA         51.0     Detchd       1931.0          Unf         Fa         TA           No          Unf       TA       TA          Unf         0.0      FuseF
9       NaN         NaN   NaN    NaN        NaN          TA         50.0     Attchd       1939.0          RFn         Gd         TA           No          Unf       TA       TA          GLQ         0.0      SBrkr
10      NaN         NaN   NaN    NaN        NaN         NaN         70.0     Detchd       1965.0          Unf         TA         TA           No          Unf       TA       TA          Rec         0.0      SBrkr
11      NaN         NaN   NaN    NaN      Stone          Gd         85.0    BuiltIn       2005.0          Fin         TA         TA           No          Unf       Ex       TA          GLQ       286.0      SBrkr
12      NaN         NaN   NaN    NaN        NaN         NaN          NaN     Detchd       1962.0          Unf         TA         TA           No          Unf       TA       TA          ALQ         0.0      SBrkr
13      NaN         NaN   NaN    NaN      Stone          Gd         91.0     Attchd       2006.0          RFn         TA         TA           Av          Unf       Gd       TA          Unf       306.0      SBrkr
14      NaN         NaN   NaN   GdWo    BrkFace          Fa          NaN     Attchd       1960.0          RFn         TA         TA           No          Unf       TA       TA          BLQ       212.0      SBrkr
15      NaN         NaN   NaN  GdPrv        NaN         NaN         51.0     Detchd       1991.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      FuseA
16      NaN        Shed   NaN    NaN    BrkFace          TA          NaN     Attchd       1970.0          Fin         TA         TA           No          Unf       TA       TA          ALQ       180.0      SBrkr
17      NaN        Shed   NaN    NaN        NaN         NaN         72.0    CarPort       1967.0          Unf         TA         TA          NaN          NaN      NaN      NaN          NaN         0.0      SBrkr
18      NaN         NaN   NaN    NaN        NaN         NaN         66.0     Detchd       2004.0          Unf         TA         TA           No          Unf       TA       TA          GLQ         0.0      SBrkr
19      NaN         NaN   NaN  MnPrv        NaN         NaN         70.0     Attchd       1958.0          Unf         TA         TA           No          Unf       TA       TA          LwQ         0.0      SBrkr
20      NaN         NaN   NaN    NaN    BrkFace          Gd        101.0    BuiltIn       2005.0          RFn         TA         TA           Av          Unf       Ex       TA          Unf       380.0      SBrkr
21      NaN         NaN  Grvl  GdPrv        NaN          Gd         57.0     Attchd       1930.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      FuseF
22      NaN         NaN   NaN    NaN    BrkFace          Gd         75.0     Attchd       2002.0          RFn         TA         TA           No          Unf       Gd       TA          Unf       281.0      SBrkr
23      NaN         NaN   NaN    NaN        NaN          TA         44.0     Attchd       1976.0          Unf         TA         TA           No          Unf       Gd       TA          GLQ         0.0      SBrkr
24      NaN         NaN   NaN  MnPrv        NaN          TA          NaN     Attchd       1968.0          Unf         TA         TA           Mn          ALQ       TA       TA          Rec         0.0      SBrkr
25      NaN         NaN   NaN    NaN      Stone          Gd        110.0     Attchd       2007.0          RFn         TA         TA           No          Unf       Gd       TA          Unf       640.0      SBrkr
26      NaN         NaN   NaN    NaN        NaN         NaN         60.0     Detchd       2005.0          Unf         TA         TA           Mn          Rec       TA       TA          BLQ         0.0      SBrkr
27      NaN         NaN   NaN    NaN      Stone          Gd         98.0     Attchd       2008.0          RFn         TA         TA           No          Unf       Ex       TA          GLQ       200.0      SBrkr
28      NaN         NaN   NaN    NaN        NaN          Gd         47.0     Attchd       1957.0          RFn         TA         TA           Gd          Unf       TA       TA          BLQ         0.0      SBrkr
29      NaN         NaN   NaN    NaN        NaN         NaN         60.0     Detchd       1920.0          Unf         Fa         TA           No          Unf       TA       TA          Unf         0.0      SBrkr
30      NaN         NaN  Pave  MnPrv        NaN         NaN         50.0     Detchd       1920.0          Unf         TA         Fa           No          Unf       TA       TA          Unf         0.0      SBrkr
31      NaN         NaN   NaN  MnPrv        NaN         NaN          NaN     Attchd       1966.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      SBrkr
32      NaN         NaN   NaN    NaN        NaN         NaN         85.0     Attchd       2007.0          RFn         TA         TA           Av          Unf       Ex       TA          Unf         0.0      SBrkr
33      NaN         NaN   NaN    NaN        NaN          Gd         70.0     Attchd       1959.0          RFn         TA         TA           No          Unf       TA       TA          Rec         0.0      SBrkr
34      NaN         NaN   NaN    NaN    BrkFace          Gd         60.0     Attchd       2005.0          Fin         TA         TA           No          Unf       Ex       TA          GLQ       246.0      SBrkr
35      NaN         NaN   NaN    NaN      Stone          Gd        108.0    BuiltIn       2004.0          Fin         TA         TA           Av          Unf       Ex       TA          Unf       132.0      SBrkr
36      NaN         NaN   NaN    NaN        NaN         NaN        112.0     Attchd       1995.0          Unf         TA         TA           No          Unf       Gd       TA          Unf         0.0      SBrkr
37      NaN         NaN   NaN    NaN    BrkFace          TA         74.0     Attchd       1954.0          Fin         TA         TA           No          Unf       TA       TA          Rec       650.0      SBrkr
38      NaN         NaN   NaN    NaN        NaN         NaN         68.0     Detchd       1953.0          Unf         TA         TA           No          Unf       TA       TA          GLQ         0.0      SBrkr
39      NaN         NaN   NaN    NaN        NaN         NaN         65.0        NaN          NaN          NaN        NaN        NaN          NaN          NaN      NaN      NaN          NaN         0.0      FuseP
40      NaN         NaN   NaN   GdWo    BrkFace          TA         84.0     Attchd       1965.0          RFn         TA         TA           No          Unf       TA       TA          Rec       101.0      SBrkr
41      NaN         NaN   NaN    NaN        NaN          Gd        115.0     Attchd       1959.0          RFn         TA         TA           Gd          Unf       TA       TA          BLQ         0.0      SBrkr
42      NaN         NaN   NaN  MnPrv        NaN         NaN          NaN     Attchd       1983.0          RFn         TA         Gd           Av          LwQ       Gd       TA          ALQ         0.0      SBrkr
43      NaN         NaN   NaN  MnPrv        NaN         NaN          NaN     Detchd       1977.0          Unf         TA         TA           Av          BLQ       Gd       TA          LwQ         0.0      SBrkr
44      NaN         NaN   NaN    NaN        NaN         NaN         70.0     Attchd       1959.0          RFn         TA         TA           No          BLQ       TA       TA          ALQ         0.0      FuseA
45      NaN         NaN   NaN    NaN    BrkFace          Gd         61.0     Attchd       2005.0          RFn         TA         TA           No          Unf       Ex       TA          GLQ       412.0      SBrkr
46      NaN         NaN   NaN    NaN        NaN          Ex         48.0     Attchd       2003.0          RFn         TA         TA           No          Unf       Ex       TA          GLQ         0.0      SBrkr
47      NaN         NaN   NaN    NaN        NaN         NaN         84.0     Attchd       2006.0          RFn         TA         TA           Av          Unf       Gd       TA          GLQ         0.0      SBrkr
48      NaN         NaN   NaN    NaN        NaN         NaN         33.0        NaN          NaN          NaN        NaN        NaN           No          Unf       TA       TA          Unf         0.0      SBrkr
49      NaN         NaN   NaN  MnPrv        NaN         NaN         66.0     Attchd       1966.0          Unf         TA         TA           No          Unf       TA       TA          BLQ         0.0      SBrkr
50      NaN         NaN   NaN    NaN        NaN         NaN          NaN     Attchd       1997.0          Fin         TA         TA           Av          Unf       Gd       TA          GLQ         0.0      SBrkr
51      NaN        Shed   NaN  MnPrv        NaN          Gd         52.0     Detchd       1985.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      SBrkr
52      NaN         NaN   NaN    NaN        NaN         NaN        110.0    CarPort       1963.0          Unf         TA         TA           Gd          GLQ       Gd       TA          LwQ         0.0      SBrkr
53      NaN         NaN   NaN    NaN        NaN          Gd         68.0     Attchd       1981.0          Fin         TA         TA           Gd          Unf       Ex       TA          GLQ         0.0      SBrkr
54      NaN         NaN   NaN  MnPrv        NaN          TA         60.0     Detchd       1962.0          Unf         TA         TA           No          Unf       TA       TA          ALQ         0.0      SBrkr
55      NaN         NaN   NaN    NaN    BrkFace          Gd        100.0     Attchd       1964.0          RFn         TA         TA           No          Unf       TA       TA          BLQ       272.0      SBrkr
56      NaN         NaN  Pave    NaN    BrkFace         NaN         24.0     Attchd       1999.0          Fin         TA         TA           No          Unf       Gd       TA          GLQ       456.0      SBrkr
57      NaN         NaN   NaN    NaN        NaN         NaN         89.0     Attchd       2004.0          RFn         TA         TA           No          Unf       Gd       TA          Unf         0.0      SBrkr
58      NaN         NaN   NaN    NaN    BrkFace          Gd         66.0    BuiltIn       2006.0          Fin         TA         TA           Gd          Unf       Ex       TA          Unf      1031.0      SBrkr
59      NaN         NaN   NaN  MnPrv        NaN         NaN         60.0     Detchd       1973.0          Unf         TA         TA           Av          Unf       TA       TA          ALQ         0.0      SBrkr
60      NaN         NaN   NaN    NaN        NaN         NaN         63.0     Detchd       2006.0          Unf         TA         TA           No          Unf       Gd       TA          ALQ         0.0      SBrkr
61      NaN         NaN   NaN    NaN        NaN         NaN         60.0     Detchd       1935.0          Unf         TA         TA           No          Unf       TA       Fa          Unf         0.0      SBrkr
62      NaN         NaN   NaN    NaN      Stone          Gd         44.0     Attchd       2006.0          RFn         TA         TA           Mn          Unf       Gd       Gd          GLQ       178.0      SBrkr
63      NaN         NaN   NaN  GdPrv        NaN         NaN         50.0     Detchd       1990.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      SBrkr
64      NaN         NaN   NaN  GdPrv    BrkFace         NaN          NaN     Attchd       1998.0          RFn         TA         TA           No          Unf       Gd       TA          GLQ       573.0      SBrkr
65      NaN         NaN   NaN    NaN    BrkFace          Gd         76.0    BuiltIn       2004.0          RFn         TA         TA           Av          Unf       Ex       TA          Unf       344.0      SBrkr
66      NaN         NaN   NaN    NaN    BrkFace          Gd          NaN     Attchd       1970.0          RFn         TA         TA           Gd          Unf       Gd       TA          GLQ       287.0      SBrkr
67      NaN         NaN   NaN    NaN    BrkFace         NaN         72.0     Attchd       2003.0          RFn         TA         TA           Av          Unf       Gd       TA          GLQ       167.0      SBrkr
68      NaN         NaN   NaN    NaN        NaN         NaN         47.0     Attchd       1945.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      SBrkr
69      NaN         NaN   NaN    NaN        NaN          TA         81.0     Attchd       1953.0          Fin         TA         TA           No          Unf       TA       TA          BLQ         0.0      SBrkr
70      NaN         NaN   NaN    NaN    BrkFace          Gd         95.0     Attchd       1973.0          Fin         TA         TA           Gd          Unf       Gd       TA          ALQ      1115.0      SBrkr
71      NaN         NaN   NaN    NaN        NaN         NaN         69.0     Detchd       1987.0          Unf         TA         TA           No          Unf       TA       TA          ALQ         0.0      SBrkr
72      NaN         NaN   NaN    NaN    BrkFace          TA         74.0     Attchd       1998.0          Fin         TA         TA           No          Unf       Gd       TA          Unf        40.0      SBrkr
73      NaN         NaN   NaN   GdWo    BrkFace         NaN         85.0     Attchd       1989.0          Unf         TA         TA           No          BLQ       TA       TA          ALQ       104.0      SBrkr
74      NaN         NaN   NaN    NaN        NaN         NaN         60.0     Detchd       1915.0          Unf         TA         TA           No          Unf       Fa       TA          Unf         0.0      SBrkr
75      NaN         NaN   NaN   GdWo        NaN         NaN         21.0    BuiltIn       1973.0          Unf         TA         TA           Gd          Unf       Gd       TA          GLQ         0.0      SBrkr
76      NaN         NaN   NaN    NaN        NaN         NaN          NaN     Detchd       1956.0          Unf         TA         TA           No          Unf       TA       TA          ALQ         0.0      FuseA
77      NaN         NaN   NaN  MnPrv        NaN         NaN         50.0     Detchd       1948.0          Unf         TA         TA           No          GLQ       TA       TA          BLQ         0.0      SBrkr
78      NaN         NaN   NaN    NaN        NaN         NaN         72.0        NaN          NaN          NaN        NaN        NaN           No          Unf       TA       TA          Unf         0.0      SBrkr
79      NaN         NaN  Grvl  MnPrv        NaN         NaN         60.0     Detchd       1966.0          Unf         TA         TA           No          Unf       TA       TA          Unf         0.0      SBrkr
80      NaN         NaN   NaN    NaN    BrkFace          Gd        100.0     Attchd       1968.0          Fin         TA         TA           No          Unf       Gd       TA          Rec       576.0      SBrkr
81      NaN         NaN   NaN    NaN    BrkFace         NaN         32.0     Attchd       1998.0          Fin         TA         TA           No          Unf       Ex       Gd          GLQ       443.0      SBrkr
82      NaN         NaN   NaN    NaN      Stone          Gd         78.0     Attchd       2007.0          RFn         TA         TA           No          Unf       Gd       TA          GLQ       468.0      SBrkr
83      NaN         NaN   NaN    NaN     BrkCmn         NaN         80.0     Detchd       1974.0          Unf         TA         TA           No          Unf       TA       TA          Unf        66.0      SBrkr
84      NaN        Shed   NaN    NaN    BrkFace          TA          NaN    BuiltIn       1995.0          Fin         TA         TA           No          Unf       Gd       TA          Unf        22.0      SBrkr
85      NaN         NaN   NaN    NaN    BrkFace          TA        121.0     Attchd       1991.0          Unf         TA         TA           No          Unf       Gd       TA          Unf       284.0      SBrkr
86      NaN         NaN   NaN    NaN        NaN          Gd        122.0    BuiltIn       2005.0          Fin         TA         TA           Av          Unf       Gd       TA          Unf         0.0      SBrkr
87      NaN         NaN  Pave    NaN      Stone         NaN         40.0     Detchd       2009.0          RFn         TA         TA           Av          Unf       Gd       TA          Unf        76.0      SBrkr
88      NaN         NaN   NaN  MnPrv        NaN         NaN        105.0        NaN          NaN          NaN        NaN        NaN           No          Unf       TA       Fa          Unf         0.0      SBrkr
89      NaN         NaN   NaN    NaN        NaN         NaN         60.0        NaN          NaN          NaN        NaN        NaN           No          Unf       Gd       TA          GLQ         0.0      SBrkr
90      NaN         NaN   NaN    NaN        NaN         NaN         60.0     Detchd       1950.0          Unf         TA         TA          NaN          NaN      NaN      NaN          NaN         0.0      FuseA
91      NaN         NaN   NaN   GdWo     BrkCmn         NaN         85.0     Attchd       1961.0          Unf         TA         TA           No          Unf       TA       TA          Rec       203.0      SBrkr
92      NaN         NaN  Grvl    NaN        NaN         NaN         80.0     Detchd       1921.0          Unf         TA         TA           No          Unf       Gd       TA          ALQ         0.0      SBrkr

In [9]:
basement_cols = ['BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtCond', 'BsmtFinType1']
#df[df[basement_cols].isnull().any(axis=1)][basement_cols]
df.loc[df[basement_cols].isnull().any(axis=1),basement_cols]

     BsmtExposure BsmtFinType2 BsmtQual BsmtCond BsmtFinType1
17            NaN          NaN      NaN      NaN          NaN
39            NaN          NaN      NaN      NaN          NaN
90            NaN          NaN      NaN      NaN          NaN
102           NaN          NaN      NaN      NaN          NaN
156           NaN          NaN      NaN      NaN          NaN
182           NaN          NaN      NaN      NaN          NaN
259           NaN          NaN      NaN      NaN          NaN
332            No          NaN       Gd       TA          GLQ
342           NaN          NaN      NaN      NaN          NaN
362           NaN          NaN      NaN      NaN          NaN
371           NaN          NaN      NaN      NaN          NaN
392           NaN          NaN      NaN      NaN          NaN
520           NaN          NaN      NaN      NaN          NaN
532           NaN          NaN      NaN      NaN          NaN
533           NaN          NaN      NaN      NaN          NaN
553           NaN          NaN      NaN      NaN          NaN
646           NaN          NaN      NaN      NaN          NaN
705           NaN          NaN      NaN      NaN          NaN
736           NaN          NaN      NaN      NaN          NaN
749           NaN          NaN      NaN      NaN          NaN
778           NaN          NaN      NaN      NaN          NaN
868           NaN          NaN      NaN      NaN          NaN
894           NaN          NaN      NaN      NaN          NaN
897           NaN          NaN      NaN      NaN          NaN
948           NaN          Unf       Gd       TA          Unf
984           NaN          NaN      NaN      NaN          NaN
1000          NaN          NaN      NaN      NaN          NaN
1011          NaN          NaN      NaN      NaN          NaN
1035          NaN          NaN      NaN      NaN          NaN
1045          NaN          NaN      NaN      NaN          NaN
1048          NaN          NaN      NaN      NaN          NaN
1049          NaN          NaN      NaN      NaN          NaN
1090          NaN          NaN      NaN      NaN          NaN
1179          NaN          NaN      NaN      NaN          NaN
1216          NaN          NaN      NaN      NaN          NaN
1218          NaN          NaN      NaN      NaN          NaN
1232          NaN          NaN      NaN      NaN          NaN
1321          NaN          NaN      NaN      NaN          NaN
1412          NaN          NaN      NaN      NaN          NaN

## Handle missing values

In [10]:
basement_cols = ['BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtCond', 'BsmtFinType1']
for col in basement_cols:
    df[col] = df[col].fillna('None')

In [11]:
none_cols = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu',
             'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'MasVnrType']
for col in none_cols:
    df[col] = df[col].fillna('None')

In [12]:
df['GarageYrBlt'] = df['GarageYrBlt'].fillna(0)

In [13]:
df['LotFrontage'] = df['LotFrontage'].fillna(df['LotFrontage'].median())
df['MasVnrArea'] = df['MasVnrArea'].fillna(0)
df['Electrical'] = df['Electrical'].fillna(df['Electrical'].mode()[0])

In [14]:
df.isnull().sum().sum()

np.int64(0)

## Univariate analysis

In [20]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,69.863699,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.117123,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,22.027677,9981.264932,1.382997,1.112799,30.202904,20.645407,180.731373,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,60.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,79.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,164.250000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [21]:
df['SalePrice'].describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64